FROM docker.io/python:3.10@sha256:57a1551f66ab235f86bc3c1fc2bc2c5c1632d26171d238b68bd02a67bdb180e2 as algorand-contracts-build

RUN python3 -m pip install virtualenv
COPY Pipfile.lock Pipfile.lock
COPY Pipfile Pipfile

RUN python3 -m pip install pipenv
RUN pipenv install
RUN mkdir teal
COPY *.py .

RUN pipenv run python3 admin.py --mainnet --genTeal 

FROM scratch AS algorand-contracts-export
COPY --from=algorand-contracts-build /teal/* .


